[package]
name = "zero2prod"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
chrono = { version = "0.4.26", default-features = false, features = ["clock"] }
config = "0.13.3"
reqwest = "0.11.18"
serde = { version = "1.0.163", features = ["derive"] }
sqlx = { features = ["postgres", "macros", "runtime-actix-rustls", "chrono", "uuid", "migrate"] }
tokio = "1.28.2"
uuid = { version = "1.3.3", features = ["v4"] }
